[workspace]
resolver = "3"
members = ["crates/asphodel-core", "crates/asphodel"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "MIT"
repository = "https://github.com/tim-smart/asphodel"

[workspace.dependencies]
asphodel-core = { path = "crates/asphodel-core" }

anyhow = "1"
axum = "0.8"
clap = { version = "4", features = ["derive", "env"] }
jiff = { version = "0.2", features = ["serde"] }
libc = "0.2"
rusqlite = { version = "0.40", features = ["bundled", "backup"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sqlite-vec = "0.1.9"
thiserror = "2"
toml = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
url = "2"
uuid = { version = "1", features = ["v7", "serde"] }

[workspace.lints.clippy]
disallowed_methods = "deny"
