-- Asphodel schema, version 7: where a mention was said.
--
-- Forget erases a chain behind the chunks queued before it, and those chunks
-- reconcile against the hidden memory. A claim that's a new version of the
-- memory joins its chain with a span of its own, but a claim that's only
-- `mentioned_again` or `confirmed` leaves an access, and an access recorded
-- only its source. The erase couldn't tell which part of the turn or document
-- restated the forgotten memory.
--
-- `spans` is a JSON array of `[chunk, start, end]`: the chunk's rowid and
-- character offsets into its text, the same units as
-- `memories.source_start` and `source_end`. It holds every claim that was a
-- mention of the memory, merged into its one access, which for a document
-- can come from more than one chunk. It's NULL for `created` and `used`
-- accesses, which point at no passage of their own, and for every access
-- written before version 7.
ALTER TABLE accesses ADD COLUMN spans TEXT;
